[tox]
isolated_build = true
envlist = ruff, mypy, ruff-lint
requires = tox-uv

[testenv]
passenv = *
runner = uv-venv-runner

[testenv:ruff]
description = 'Execute static analysis with ruff.'
commands = uv run ruff format . --check

[testenv:ruff_lint]
description = 'Execute static analysis with Ruff.'
commands = uv run ruff check radar_timeline_data/main.py

[testenv:mypy]
description = 'Execute static analysis with mypy.'
commands =  uv run mypy --config-file mypy.ini radar_timeline_data/ --exclude radar_timeline_data/utils/treatments.py
